DROP TABLE IF EXISTS purchase_order;

CREATE TABLE purchase_order (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID VARCHAR(150) NOT NULL,
    TOTAL_AMOUNT DECIMAL(5,2) NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    ORDER_STATUS VARCHAR(30) NOT NULL,
    ANALYTICS_SYNCED BOOL NOT NULL
);