DROP TABLE IF EXISTS export_job;

CREATE TABLE export_job (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    JOB_ID VARCHAR(150) NOT NULL,
    EXPORT_TYPE VARCHAR(150) NOT NULL,
    STATUS VARCHAR(30) NOT NULL
);

INSERT INTO export_job (JOB_ID, EXPORT_TYPE, STATUS)
VALUES ('a5dab53c-55b5-4bd8-96e2-a8fa83858827', 'PURCHASE_ORDER', 'PENDING');