DROP TABLE IF EXISTS export_job;

CREATE TABLE export_job (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    JOB_ID VARCHAR(150) NOT NULL,
    EXPORT_TYPE VARCHAR(150) NOT NULL,
    STATUS VARCHAR(30) NOT NULL
);

INSERT INTO export_job (JOB_ID, EXPORT_TYPE, STATUS)
VALUES ('e97491eb-0157-4a1d-80b6-922d0e5fa725', 'PURCHASE_ORDER', 'PENDING');